[fixes #26] Implement LMS & NLMS adaptive filter
psambit9791/jDSP pull request #30
Opened 2021-11-15 23:41 UTC by SiboVG

This PR implements the LMS and NLMS adaptive filter.

@psambit9791 in the light of how padasip implements its functions, I used a 'run()'-method for running the filtering algorithm. This got me thinking whether it would be an idea to use this terminology in the other classes as well? So instead of having to call the 'dft()'-method on a DiscreteFourier-object, you would just have to call the 'run()'-method. In this way, the user only has to "remember" one method, i.e. the run-method, instead of knowing 'I have to run 'dft()' for a DiscreteFourier, stft() for ShortTimeFourier etc. I think this could generalize and simplify jDSP. What is your opinion on this?

2021-11-15 23:46 UTC, psambit9791 commented
So, regarding your comment about using 'run()', the latest commit on master converts all "dft()" "hilbert()" etc to simply "transform()" based on the sklearn implementations of some similar functions.

So at the moment, building any object of the transform package and calling the transform() function using the object would run the specific transform. Chose transform() instead of run() because it seemed more intuitive.

2021-11-16 10:49 UTC, SiboVG commented
Ah alright, wasn't aware of that change, great :) you wanna change all the methods for the filters to 'filter()' then

2021-11-16 11:14 UTC, psambit9791 commented
That would make sense. But think it should be limited to the adaptive filters for now. The IIR filters have different initialisation depending on the type of filter so I would let them be as they are.

2021-11-16 11:25 UTC, SiboVG commented
Alright, latest commit fixed it

2021-11-16 11:40 UTC, psambit9791 requested changes

2021-11-16 11:40 UTC, psambit9791 commented on src/main/java/com/github/psambit9791/jdsp/filter/adaptive/LMSFilter.java
> +public class LMSFilter {
Just call this LMS, conforming to the classes in ```transform``` and ```filter``` package.

2021-11-16 11:40 UTC, psambit9791 commented on src/main/java/com/github/psambit9791/jdsp/filter/adaptive/LMSFilter.java
> + * @author SiboVanGool
Keep the name consistent between files. I think I saw "Sibo Van Gool" (with spaces) in another file.

2021-11-16 11:40 UTC, psambit9791 commented on src/main/java/com/github/psambit9791/jdsp/filter/adaptive/NLMSFilter.java
> + * @author SiboVanGool
Same as above

2021-11-16 11:40 UTC, psambit9791 commented on src/main/java/com/github/psambit9791/jdsp/filter/adaptive/NLMSFilter.java
> +public class NLMSFilter {
Same as above

2021-11-16 16:18 UTC, merged